server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sz_mid?useUnicode=true&amp;characterEncoding=utf8&amp;allowMultiQueries=true&amp;useSSL=false
    username : root
    password : root
    druid:
      #下面配置说明请参考Druid Github Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        login-username: root
        login-password: druid
        allow: 192.168.1.29
  redisson:
    address: redis://localhost:6379